/* eslint-disable @next/next/no-img-element */
/* eslint-disable react/jsx-no-comment-textnodes */

import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Link from 'next/link';

// API Placeholder
const defaultEndpoint = `https://my-json-server.typicode.com/mrb4le/demo/db/`;

// Fetch API
export async function getServerSideProps() {
  const res = await fetch(defaultEndpoint)
  const data = await res.json();

  return {
    props: {
      data
    }
  }

}

export default function Home({ data }) {
  const { tichampions = [] } = data;
  console.log(data)
  return (
    <div className={styles.container}>
      <Head>
        <title>Dota 2 The International Champion</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>

        <h1 className={styles.title}>
          Dota 2 The International Champion
        </h1>

        <p className={styles.description}>
        The International, often abbreviated as TI, is an annual esports world championship tournament for the video game Dota 2, 
        hosted and produced by the game developer, Valve. professional DotA teams fight for the title of best Dota 2 team. 
        Winners of The International are awarded large sums of money raised by the community, 
        as well as the Aegis of Champions
        </p>

        <ul className={styles.grid}>
          {tichampions.map(result => {
            const {id, year, team, player, image} = result;
            return (
              <li key={id} className={styles.card}>
              <h4>{ year }</h4>
              <Link href="/champion/[id]" as={`/champion/${id}`}>
              <a>
                <img 
                src={image} 
                alt={`${team}`}
                height='300'
                width='300'
                />
                <h4>{ team }</h4>
                </a>
                </Link>
              </li>
            )
          })}
        </ul>

      </main>


      <footer className={styles.footer}>
        <a
          href="#"
          rel="noopener noreferrer"
        >
        This is a fan site not associated with or endorsed by Valve Corporation.<br></br>
        Some images are provided by Wykrhm Reddy, VPEsports, Valve.<br></br>
        
        {/* <span className={styles.logo}>
        Powered by{''} <img src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
        </span> */}
        </a>
      </footer>
    </div>
  )
}
