import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

const defaultEndpoint = `https://my-json-server.typicode.com/mrb4le/demo/db/`;

export async function getServerSideProps() {
  const res = await fetch(defaultEndpoint)
  const data = await res.json();

  return {
    props: {
      data
    }
  }

}


export default function Home({ data }) {
  const { tichampions = [] } = data;
  console.log(data)
  return (
    <div className={styles.container}>
      <Head>
        <title>Dota 2 Ti Champs</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Dota 2 Next Js APP
        </h1>

        <p className={styles.description}>
          Dota 2 Ti Champs
        </p>

        {/* <form className="search" onSubmit={handleOnSubmitSearch}>
          <input name="query" type="search"/>
          <button>Search</button>
        </form> */}

        <ul className={styles.grid}>
          {tichampions.map(result => {
            const {id, year, team, image} = result;

            return (
              <li key={id} className={styles.card}>
              <a href="https://nextjs.org/docs" >
                <img src={image} alt={`${team}`}></img>
                <h4>{ year }</h4>
                <h4>{ team }</h4>
                </a>
              </li>
            )
          })}

          {/* <button onClick={handleLoadMore}>Load More</button> */}


          
        </ul>
      </main>


      

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
