import Head from 'next/head'
import styles from '../styles/Home.module.css'
const defaultEndpoint = `https://my-json-server.typicode.com/mrb4le/demo/db/`;

export async function getServerSideProps() {
  const res = await fetch(defaultEndpoint)
  const data = await res.json();

  return {
    props: {
      data
    }
  }

}


export default function Home({ data }) {
  const { tichampions = [] } = data;
  console.log(data)
  return (
    <div className={styles.container}>
      <Head>
        <title>Dota 2 The International Champion</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Dota 2 The International Champion
        </h1>

        <p className={styles.description}>
        The International, often abbreviated as TI, is an annual esports world championship tournament for the video game Dota 2, 
        hosted and produced by the game's developer, Valve. professional DotA teams fight for the title of best Dota 2 team. 
        Winners of The International are awarded large sums of money raised by the community, 
        as well as the Aegis of Champions
        </p>

        {/* <form className="search" onSubmit={handleOnSubmitSearch}>
          <input name="query" type="search"/>
          <button>Search</button>
        </form> */}

        <ul className={styles.grid}>
          {tichampions.map(result => {
            const {id, year, team, player, image} = result;
            return (
              <li key={id} className={styles.card}>
              <h4>{ year }</h4>
              <a href={image} >
                <img 
                src={image} 
                alt={`${team}`}
                height='300'
                width='300'
                />
                <h4>{ team }</h4>
                <h4>{ player }</h4>
                </a>
              </li>
            )
          })}

          {/* <button onClick={handleLoadMore}>Load More</button> */}

        </ul>
      </main>


      

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <img src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
